PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX phs: <https://github.com/sergeitarasov/PhenoScript/>

# obo:CARO_0000000 'anatomical entity'
# obo:BFO_0000020 'specifically dependent continuant'

SELECT ?Entity ?Entity_label ?Edge ?quality_label
WHERE {
  {
    ?Entity obo:BFO_0000051 ?quality .
  }
    UNION
  {
    ?quality obo:BFO_0000050 ?Entity .
  }
  ?Entity rdfs:label ?Entity_label .
  ?quality rdf:type/rdfs:subClassOf* obo:BFO_0000020 .
  ?quality rdfs:label ?quality_label .

}

#robot query --input output/grebennikovius_merged.owl --query sparql/has_part-quality.sparql sparql/has_part-quality.csv